name: SUPERSADAP.COM
description: Sadap Berbagai Handphone Android, Blackberry, Nokia, Iphone dan Fitur Sadap BBM SMS Panggilan Suara, Lokasi dan Whatsapp
markdown: redcarpet
baseurl: '/'
url: https://supersadap.com
enforce_ssl: supersadap.com

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed


compress_html:
  comments: ["<!-- ", " -->"]

facebook:
  app_id: 547297888787869
