name: SUPERSADAP.COM
markdown: redcarpet
baseurl: '/'
url: https://supersadap.com
enforce_ssl: supersadap.com

gems:
  - jekyll-sitemap
  - jekyll-seo-tag


compress_html:
  comments: ["<!-- ", " -->"]
